name: AstrowayCustomer
description: The Astrology app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  #UI DESIGN
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  flutter_rating_bar: ^4.0.1
  flutter_html: ^3.0.0-alpha.5
  bubble_tab_indicator: ^0.1.6
  flutter_image_slideshow: ^0.1.6
  date_format: 2.0.7
  video_player: ^2.9.1
  percent_indicator: ^4.2.3
  photo_view: ^0.14.0
  custom_clippers: ^2.0.0
  url_launcher: ^6.3.0

  #MULTI-LANGUAGE
  easy_localization: ^3.0.5

  #WEBVIEW
  flutter_inappwebview: ^6.0.0

  #TOAST MESSAGE
  fluttertoast: ^8.1.1

  #AGORA
  agora_rtm: ^1.5.9
  agora_rtc_engine: ^6.5.0
  #SYSTEM PERMISSION
  permission_handler: ^11.3.1
  path_provider: ^2.1.4

  #OTP
  #  flutter_otp_text_field: ^1.1.1

  #DEVICE INFO
  device_info_plus: ^9.1.2

  #CONNECTIVITY
  connectivity_plus: ^6.1.1
  http: ^1.2.2

  #LOCATION
  geocoding: ^3.0.0
  flutter_google_places_sdk: ^0.3.7

  #PDF VIEWER
  syncfusion_flutter_pdfviewer: ^24.1.41

  #REDIRECT
  store_redirect: ^2.0.1

  #SCORE
  syncfusion_flutter_gauges: ^24.2.9

  #PLATFORM INFO
  package_info_plus: ^8.0.0
  flutter_countdown_timer: ^4.1.0

  #DATE TIME PICKER
  flutter_holo_date_picker: ^1.1.0
  flutter_time_picker_spinner: ^2.0.0
  #screenshot: ^2.1.0

  #STATE MANAGEMENT
  get: ^4.6.6

  #RAZOR_PAY
  #razorpay_flutter: ^1.3.6

  #FIREBASE
  #firebase_core: ^3.1.1
  firebase_core: ^3.10.0
  #firebase_messaging: ^15.0.1
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^17.2.1+2
  #cloud_firestore: ^5.1.0
  cloud_firestore: ^5.6.1
  googleapis_auth: ^1.6.0
  firebase_storage: ^12.1.0

  #LOCAL STORAGE
  shared_preferences: ^2.3.1

  #  intl_phone_field: ^3.1.0
  intl_phone_number_input: ^0.7.4
  flutter_share: ^2.0.0

  #IMAGE
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  cached_network_image: ^3.4.0

  marquee: ^2.2.3

  #Audioplayer
  audioplayers: ^6.1.0
  flutter_screen_wake: ^1.0.2

  #YOUTUBE PLAYER
  youtube_player_flutter: ^9.0.0

  #PDF
  pdf: ^3.11.0
  share_plus: ^10.0.0

  uuid: ^4.4.0

  draggable_widget: ^2.0.0
  responsive_sizer: ^3.3.0+1

  intl: any

  story_view: ^0.16.5
  swipe_to: ^1.0.6
  file_picker: ^8.0.0+1
  open_file: ^3.3.2
  lecle_yoyo_player: ^0.0.8
  otpless_flutter: ^2.1.4
  pin_input_text_field: ^4.5.1
  flutter_callkit_incoming: ^2.0.4+1
  get_storage: ^2.1.1
  logger: ^2.4.0
  flutter_svg: ^2.0.10+1
  timelines_plus: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  # flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/translations/
    - assets/ringtone.mp3
    - lib/utils/noti_service.json

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
